namespace: cnpg-db

argoApplication:
  name: cnpg-app
  namespace: argocd

cluster:
  name: postgres-cluster
  instances: 3
  storageSize: 10Gi

secrets:
  postgres:
    secretName: postgres-secret
    dbName: postgres
    dbUser: postgres
    dbPassword: postgres

flags:
  enablePostgis: true