apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argoApplication.name }}
  namespace: {{ .Values.argoApplication.namespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-pg/charts
    targetRevision: main
    chart: charts/cloudnative-pg
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true