apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.operator.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.operator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.operator.name }}
    spec:
      serviceAccountName: {{ .Values.operator.name }}
      containers:
        - name: operator
          image: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
