apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.initdb.secretName }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secrets.postgres.initdb.dbUserAsBase64 }}
  password: {{ .Values.secrets.postgres.initdb.dbPasswordAsBase64 }}