apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.secrets.postgres.dbUser }}
  password: {{ .Values.secrets.postgres.dbPassword }}