apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.cluster.name }}-pvc"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cluster.storageSize }}
